"""
Django settings for historia_clinica project.

Generated by 'django-admin startproject' using Django 3.2.6.
"""

import os
from pathlib import Path
from mongoengine import connect

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings
SECRET_KEY = 'django-insecure-$owl@kfc0erhk6#=v2l^qj*94s$s3=+83=pzx%$yh8zfip8ab^'
DEBUG = True

# Allow requests forwarded through Kong
ALLOWED_HOSTS = [
    os.environ.get("KONG_HOST", "10.128.0.81"),
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'informacion_diagnostica',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'historia_clinica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'historia_clinica.wsgi.application'


# MongoDB connection via MongoEngine
MONGO_USER     = os.getenv("MONGO_INITDB_ROOT_USERNAME", "afgomezg1")
MONGO_PASS     = os.getenv("MONGO_INITDB_ROOT_PASSWORD", "password")
MONGO_HOST     = os.getenv("MONGO_HOST", "10.128.0.83")
MONGO_PORT     = os.getenv("MONGO_PORT", "27017")
MONGO_DB_NAME  = os.getenv("MONGO_DB_NAME", "historia_clinica_db")

MONGO_URI = (
    f"mongodb://{MONGO_USER}:{MONGO_PASS}"
    f"@{MONGO_HOST}:{MONGO_PORT}/{MONGO_DB_NAME}"
)
connect(host=MONGO_URI)


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files
STATIC_URL = '/static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# API Gateway settings
PATH_API_GATEWAY = (
    "http://"
    + os.environ.get("KONG_HOST", "10.128.0.81")
    + ":"
    + os.environ.get("KONG_PORT", "8000")
)

# Internal endpoint URLs
PERSONAL_MEDICO_INTERNAL = PATH_API_GATEWAY + "/personal-medico/internal/assignments/"
HISTORIA_CLINICA_REPORT  = PATH_API_GATEWAY + "/historia-clinica/api/report/"

# CORS
CORS_ALLOW_ALL_ORIGINS = True
